import type { Level } from "../types";

export const levels: Level[] = [
  {
    id: 1,
    name: "Straight Line",
    description: "Draw a straight line forward.",
    hint: "Use forward(100) to move the turtle.",
    targetDescription: "A single straight line going up from the center.",
    starThresholds: [1, 2, 3],
    availableCommands: ["forward", "fd"],
    starterCode: "// Move the turtle forward!\nforward(100)\n",
  },
  {
    id: 2,
    name: "Turn & Draw",
    description: "Move forward, turn, then move again.",
    hint: "Use right(90) to turn 90 degrees.",
    targetDescription: "An L-shaped line: up then right.",
    starThresholds: [3, 5, 8],
    availableCommands: ["forward", "fd", "right", "rt"],
    starterCode: "// Draw an L shape\n",
  },
  {
    id: 3,
    name: "Square",
    description: "Draw a perfect square.",
    hint: "Use repeat(4) to avoid writing the same thing 4 times!",
    targetDescription: "A square with sides of 100 pixels.",
    starThresholds: [3, 6, 10],
    availableCommands: ["forward", "fd", "right", "rt", "repeat"],
    starterCode: "// Draw a square\n",
  },
  {
    id: 4,
    name: "Triangle",
    description: "Draw an equilateral triangle.",
    hint: "The exterior angle of a triangle is 120 degrees.",
    targetDescription: "An equilateral triangle with sides of 100 pixels.",
    starThresholds: [3, 5, 8],
    availableCommands: ["forward", "fd", "right", "rt", "left", "lt", "repeat"],
    starterCode: "// Draw a triangle\n",
  },
  {
    id: 5,
    name: "Staircase",
    description: "Draw a staircase pattern going up.",
    hint: "Alternate between forward and right(90) to make steps.",
    targetDescription: "A staircase with 5 steps, each 30 pixels wide and tall.",
    starThresholds: [5, 8, 15],
    availableCommands: ["forward", "fd", "right", "rt", "left", "lt", "repeat"],
    starterCode: "// Draw a staircase\n",
  },
  {
    id: 6,
    name: "Star",
    description: "Draw a five-pointed star.",
    hint: "Turn 144 degrees after each line to make a star shape.",
    targetDescription: "A five-pointed star with sides of 100 pixels.",
    starThresholds: [3, 5, 10],
    availableCommands: ["forward", "fd", "right", "rt", "repeat"],
    starterCode: "// Draw a star\n",
  },
  {
    id: 7,
    name: "Hexagon",
    description: "Draw a regular hexagon.",
    hint: "A hexagon has 6 sides with 60-degree turns.",
    targetDescription: "A regular hexagon with sides of 60 pixels.",
    starThresholds: [3, 5, 10],
    availableCommands: ["forward", "fd", "right", "rt", "repeat"],
    starterCode: "// Draw a hexagon\n",
  },
  {
    id: 8,
    name: "House",
    description: "Draw a house (square + triangle roof).",
    hint: "Draw a square first, then position the turtle for the triangle roof.",
    targetDescription:
      "A house shape: a square base with a triangular roof on top.",
    starThresholds: [10, 15, 20],
    availableCommands: ["forward", "fd", "back", "bk", "right", "rt", "left", "lt", "repeat"],
    starterCode: "// Draw a house: square + triangle roof\n",
  },
  {
    id: 9,
    name: "Colorful Square",
    description: "Draw a square where each side is a different color.",
    hint: 'Use penColor("red") to change colors between sides.',
    targetDescription: "A square with each side a different color: red, blue, green, yellow.",
    starThresholds: [12, 16, 20],
    availableCommands: [
      "forward", "fd", "right", "rt", "penColor", "color", "repeat",
    ],
    starterCode: '// Draw a colorful square\npenColor("red")\n',
  },
  {
    id: 10,
    name: "Spiral",
    description: "Draw a spiral by increasing the distance each step.",
    hint: "The trick: each forward() is a little longer, and turn slightly more than 90 degrees.",
    targetDescription:
      "A square spiral that grows outward. Each line is 5 pixels longer than the last.",
    starThresholds: [20, 30, 50],
    availableCommands: ["forward", "fd", "right", "rt", "repeat"],
    starterCode:
      "// Draw a spiral\n// Tip: increase forward distance each time\nforward(10)\nrt(91)\nforward(15)\nrt(91)\nforward(20)\nrt(91)\n",
  },
  {
    id: 11,
    name: "Circle (approx.)",
    description: "Approximate a circle using many small steps.",
    hint: "Move a little, turn a little, repeat many times! Try repeat(36) { fd(10); rt(10) }.",
    targetDescription: "An approximate circle made from 36 tiny straight-line segments.",
    starThresholds: [3, 5, 8],
    availableCommands: ["forward", "fd", "right", "rt", "repeat"],
    starterCode: "// Draw a circle\n",
  },
  {
    id: 12,
    name: "Flower",
    description: "Draw a flower by repeating circles at angles.",
    hint: "Draw a circle, turn a bit, draw another circle. Repeat!",
    targetDescription:
      "A flower with 6 petals, each petal is a small circle rotated 60 degrees from the last.",
    starThresholds: [5, 8, 12],
    availableCommands: ["forward", "fd", "right", "rt", "repeat"],
    starterCode: "// Draw a flower\n// Each petal is a circle, rotated 60 degrees\n",
  },
  {
    id: 13,
    name: "Thick & Thin",
    description: "Use different pen sizes to draw thick and thin lines.",
    hint: "Use penSize(1) for thin and penSize(5) for thick.",
    targetDescription:
      "Alternating thick and thin lines forming a square. Thick sides are 5px, thin sides are 1px.",
    starThresholds: [10, 14, 20],
    availableCommands: [
      "forward", "fd", "right", "rt", "penSize", "repeat",
    ],
    starterCode: "// Draw with different pen sizes\npenSize(5)\n",
  },
  {
    id: 14,
    name: "Rainbow Spiral",
    description: "Draw a colorful spiral that changes color on each loop.",
    hint: "Change penColor and increase the forward distance in each iteration.",
    targetDescription:
      "A spiral that cycles through red, orange, yellow, green, blue, purple as it grows.",
    starThresholds: [30, 42, 60],
    availableCommands: [
      "forward", "fd", "right", "rt", "penColor", "color", "penSize", "repeat",
    ],
    starterCode:
      '// Rainbow spiral\n// Change color and increase size each loop\npenColor("red")\nforward(10)\nrt(91)\npenColor("orange")\nforward(15)\nrt(91)\n',
  },
  {
    id: 15,
    name: "Freestyle",
    description: "Sandbox mode! Draw whatever you want.",
    hint: "No rules. Experiment with all the commands you have learned!",
    targetDescription: "No target. Create your own masterpiece!",
    starThresholds: [1, 1, 1], // Always 3 stars
    availableCommands: [
      "forward", "fd", "back", "bk",
      "right", "rt", "left", "lt",
      "penUp", "pu", "penDown", "pd",
      "penColor", "color", "penSize",
      "repeat",
    ],
    starterCode:
      "// Freestyle! Draw anything you like.\n// Try combining everything you learned.\n",
  },
];
